export  const Introcontent = {
    title : "Front-End React",
    title1 : "Developer",
    introImage : "/Intro/Logo/introimg4.png",
    introalt : "Intro",
    introcontent : "Hi, I am Sundar. A passionate Front-end React",
    introcontent2 : "Developer based in Tamilnadu, India",
    handImage : "/Intro/Logo/hand.png",
    handalt : "hi",
    htmlImage : "/Intro/Logo/chtml.svg",
    htmlalt : "HTML",
    cssImage : "/Intro/Logo/ccss.svg",
    cssalt : "CSS",
    jsImage : "/Intro/Logo/JavaScript.svg",
    jsalt : "Javascript",
    reactImage : "/Intro/Logo/creact.svg",
    reactalt : "react",
    nextImage : "/Intro/Logo/cnext.svg",
    nextalt : "Next",
    tailwindImage : "/Intro/Logo/ctailwind.svg",
    tailwindalt : "tailwind",
    sassImage : "/Intro/Logo/csass.svg",
    sassalt : "sass",
    githuplink : "https://github.com/sundarsaravanansk",
    githupImage : "/social/github.png",
    githupalt : "github",
    Linkedinlink : "https://www.linkedin.com/in/sundar-sk-52112a281/",
    LinkedinImage : "/social/link.png",
    Linkedinalt : "linkedin",
}